######################################################################
##
## Filename: sp6.udo
## Created on: Thu Jun 18 11:19:47 中国标准时间 2020
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
